schema_version = 1
migration_id = "2363acce859a449d93e86d017a363683"
project_uuid = "816e173a-3ffa-4a95-80bd-6da6f6e3a54e"
phase = "complete"

[items.0]
component = "mount"
tool = "taskledger"
mount = "data"
source = "/data/data/com.termux/files/home/src/ledger/task/booktx"
destination = "/data/data/com.termux/files/home/src/ledger/taskledger/816e173a-3ffa-4a95-80bd-6da6f6e3a54e/data"
strategy = "copy"
